### ISSUE TITLE
I want to use AttributedLabel in dynamic cell.

### ISSUE THREAD

**Issue by vkcldhkd** [KyoheiG3/AttributedLabel#11]
I want to use AttributedLabel in dynamic cell.
However, the AttributedLabel must have a fixed height.
AttributedLabel is too fast compared to UILabel, so I want to use it.

**Comment by KyoheiG3** [comment]
Thank you for your new issue. I try to consider it.

**Comment by KyoheiG3** [comment]
It was supported.
Please use `var intrinsicAutoLayout: Bool` and check README about the flag.
