### ISSUE TITLE
Any further insights on the performence difference?

### ISSUE THREAD

**Issue by openaphid** [KyoheiG3/AttributedLabel#4]
I used Time Profiler to find what's slowing down `UILabel` in this particular benchmark. And it seems a large portion of time was spent on `-[UILabel updateConstraints]`.

During scrolling, `-[UILabel updateConstrains]` was invoked for hundreds of times, while `-[AttributedLabel updateConstrains]` was only called for only 61 times.

I'll look into it for more clues if I get more time.

Thanks for your project. It indicates that `UILabel` can be the performance bottleneck for trivial text drawing tasks.

**Comment by KyoheiG3** [comment]
Is it called 61 times in `AttributeLabel` when the creation of an instance. However, `UILabel` is called every time `prepareForReuse` of Cell.

`updateConstrains` might be related to the layout of Cell.

Thanks.

**Comment by Elshad** [comment]
Is it possible extend `UILabel` and override `drawRect` and get speed as `AttributeLabel` ? Did you try this solution?

**Comment by KyoheiG3** [comment]
Yes, I tried. Didn't get same speed only override of drawRect.
